import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import SideNav from './ui/sidenav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-bg-100 flex flex-col md:flex-row h-screen`}>
        <div className='w-full flex-none md:w-64'>
        <SideNav />
        </div>
        {children}
      </body>
    </html>
  )
}
